'use client'

import { useState } from 'react'
import { ChevronLeft, ChevronRight } from 'lucide-react'

interface AboutPageProps {
  onBack: () => void
}

const TERMS_OF_USE = `TERMS OF USE — GROZL AI
Last updated: January 2025

1. ACCEPTANCE OF TERMS
By accessing or using Grozl ("the App"), you agree to be bound by these Terms of Use. If you do not agree, please do not use the App.

2. DESCRIPTION OF SERVICE
Grozl is an AI-powered chat assistant that uses third-party AI models (including Groq's Llama and Google's Gemini) to generate responses. The App is provided for informational and productivity purposes only.

3. USER RESPONSIBILITIES
• You must be at least 13 years of age to use this App.
• You are responsible for all activity that occurs under your account.
• You agree not to use the App for any illegal, harmful, or abusive purpose.
• You must not attempt to reverse-engineer, hack, or disrupt the App's services.
• You must not use the App to generate content that is harmful, threatening, defamatory, obscene, or violates the rights of others.

4. AI-GENERATED CONTENT DISCLAIMER
All content generated by Grozl is produced by AI models and is provided "as-is" for reference only. Grozl does not guarantee the accuracy, completeness, or reliability of any AI-generated content. You should independently verify any important information before acting on it.

5. INTELLECTUAL PROPERTY
The Grozl name, logo, and all associated branding are the property of the Grozl team. AI-generated responses do not constitute original works owned by Grozl or by users.

6. LIMITATION OF LIABILITY
To the maximum extent permitted by law, Grozl and its developers shall not be liable for any indirect, incidental, or consequential damages arising from your use of the App.

7. CHANGES TO TERMS
We reserve the right to modify these Terms at any time. Continued use of the App after changes constitutes acceptance of the new Terms.

8. GOVERNING LAW
These Terms are governed by the laws of India.

9. CONTACT
For questions about these Terms, contact us at: grozlteam@gmail.com`

const PRIVACY_POLICY = `PRIVACY POLICY — GROZL AI
Last updated: January 2025

1. INFORMATION WE COLLECT

a) Account Information
When you sign in with Google, we receive your email address and profile information from Google OAuth. We use this only to identify your account.

b) Chat Data
Your conversations with Grozl are stored in our secure database (Supabase) to enable chat history and memory features. We do not sell or share your conversations with third parties.

c) Memory Data
If you enable the Memory feature, we store a summary of facts you share with Grozl to personalise future responses. You can view, edit, or delete this memory at any time from Settings > Memory.

d) Usage Data
We may collect anonymised usage analytics (e.g., feature usage frequency) to improve the App. This data does not identify you personally.

2. HOW WE USE YOUR INFORMATION
• To provide and personalise the Grozl AI experience.
• To maintain your chat history across sessions.
• To improve app features and fix bugs.
• We do NOT use your conversations to train AI models.
• We do NOT sell your personal data.

3. DATA SHARING
Your data is shared only with:
• Supabase (secure database hosting)
• Groq and Google (AI inference — only your messages are sent, not your account info)

All third-party providers are bound by their own privacy policies and data processing agreements.

4. DATA RETENTION
• Chat history is retained until you delete it from Settings > Data Controls.
• Memory data is retained until you clear it from Settings > Memory.
• Account data is retained until you delete your account.

5. YOUR RIGHTS
You have the right to:
• Access the data we hold about you.
• Delete your account and all associated data at any time via Settings > Account.
• Request a copy of your data by emailing us.

6. SECURITY
We use industry-standard security measures including encrypted connections (HTTPS) and secure database access controls. However, no method of transmission over the Internet is 100% secure.

7. CHILDREN'S PRIVACY
Grozl is not intended for children under 13. We do not knowingly collect personal information from children under 13.

8. CHANGES TO THIS POLICY
We may update this Privacy Policy from time to time. We will notify you of significant changes within the App.

9. CONTACT US
For privacy-related questions or data requests:
Email: grozlteam@gmail.com`

export default function AboutPage({ onBack }: AboutPageProps) {
  const [subPage, setSubPage] = useState<'main' | 'terms' | 'privacy' | 'help'>('main')
  const [versionToast, setVersionToast] = useState(false)

  const showVersionToast = () => {
    setVersionToast(true)
    setTimeout(() => setVersionToast(false), 2500)
  }

  if (subPage === 'terms') {
    return (
      <div className="flex h-full flex-col bg-[#F2F2F7]">
        <div className="flex items-center gap-3 bg-[#F2F2F7] px-4 py-4 pt-6">
          <button onClick={() => setSubPage('main')} className="flex h-8 w-8 items-center justify-center rounded-full text-gray-600 transition hover:bg-gray-200">
            <ChevronLeft className="h-5 w-5" />
          </button>
          <h1 className="text-[17px] font-semibold text-gray-900">Terms of Use</h1>
        </div>
        <div className="flex-1 overflow-y-auto px-4 py-2">
          <div className="rounded-2xl bg-white px-4 py-5">
            <pre className="whitespace-pre-wrap text-[13px] leading-relaxed text-gray-700 font-sans">{TERMS_OF_USE}</pre>
          </div>
        </div>
      </div>
    )
  }

  if (subPage === 'privacy') {
    return (
      <div className="flex h-full flex-col bg-[#F2F2F7]">
        <div className="flex items-center gap-3 bg-[#F2F2F7] px-4 py-4 pt-6">
          <button onClick={() => setSubPage('main')} className="flex h-8 w-8 items-center justify-center rounded-full text-gray-600 transition hover:bg-gray-200">
            <ChevronLeft className="h-5 w-5" />
          </button>
          <h1 className="text-[17px] font-semibold text-gray-900">Privacy Policy</h1>
        </div>
        <div className="flex-1 overflow-y-auto px-4 py-2">
          <div className="rounded-2xl bg-white px-4 py-5">
            <pre className="whitespace-pre-wrap text-[13px] leading-relaxed text-gray-700 font-sans">{PRIVACY_POLICY}</pre>
          </div>
        </div>
      </div>
    )
  }

  if (subPage === 'help') {
    return (
      <div className="flex h-full flex-col bg-[#F2F2F7]">
        <div className="flex items-center gap-3 bg-[#F2F2F7] px-4 py-4 pt-6">
          <button onClick={() => setSubPage('main')} className="flex h-8 w-8 items-center justify-center rounded-full text-gray-600 transition hover:bg-gray-200">
            <ChevronLeft className="h-5 w-5" />
          </button>
          <h1 className="text-[17px] font-semibold text-gray-900">Help &amp; Feedback</h1>
        </div>
        <div className="flex-1 overflow-y-auto px-4 py-2">
          <div className="overflow-hidden rounded-2xl bg-white">
            <a
              href="mailto:grozlteam@gmail.com?subject=Bug Report&body=Describe the bug here..."
              className="flex w-full items-center justify-between px-4 py-4 transition active:bg-gray-50"
            >
              <div className="flex items-center gap-3">
                <span className="text-[20px]">📧</span>
                <div>
                  <p className="text-[15px] text-gray-800">Email Support</p>
                  <p className="text-[12px] text-gray-400">grozlteam@gmail.com</p>
                </div>
              </div>
              <ChevronRight className="h-4 w-4 text-gray-400" />
            </a>
          </div>
          <p className="mt-4 px-1 text-center text-[12px] text-gray-400">
            We typically respond within 24–48 hours.
          </p>
        </div>
      </div>
    )
  }

  return (
    <div className="flex h-full flex-col bg-[#F2F2F7]">
      {/* Header */}
      <div className="flex items-center gap-3 bg-[#F2F2F7] px-4 py-4 pt-6">
        <button onClick={onBack} className="flex h-8 w-8 items-center justify-center rounded-full text-gray-600 transition hover:bg-gray-200">
          <ChevronLeft className="h-5 w-5" />
        </button>
        <h1 className="text-[17px] font-semibold text-gray-900">About</h1>
      </div>

      <div className="flex-1 overflow-y-auto px-4 py-2">
        {/* App info card */}
        <div className="mb-6 flex flex-col items-center rounded-2xl bg-white px-4 py-6">
          <img src="/logo.png" alt="Grozl" className="mb-3 h-16 w-16 object-contain" />
          <p className="text-[19px] font-bold text-gray-900">Grozl AI</p>
          <p className="text-[13px] text-gray-400">All the World's Best AI. One Platform.</p>
        </div>

        {/* About section */}
        <p className="mb-2 px-1 text-[13px] text-gray-500">About</p>
        <div className="mb-6 overflow-hidden rounded-2xl bg-white">
          <button
            onClick={showVersionToast}
            className="flex w-full items-center justify-between px-4 py-4 transition active:bg-gray-50"
          >
            <div className="flex items-center gap-3">
              <svg className="h-5 w-5 text-gray-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="10" /><line x1="12" y1="8" x2="12" y2="12" /><line x1="12" y1="16" x2="12.01" y2="16" />
              </svg>
              <span className="text-[15px] text-gray-800">Check for updates</span>
            </div>
            <div className="flex items-center gap-1 text-gray-400">
              <span className="text-[13px]">v1.0.0</span>
              <ChevronRight className="h-4 w-4" />
            </div>
          </button>
        </div>

        {/* Service agreement */}
        <p className="mb-2 px-1 text-[13px] text-gray-500">Legal</p>
        <div className="mb-6 overflow-hidden rounded-2xl bg-white">
          <button
            onClick={() => setSubPage('terms')}
            className="flex w-full items-center justify-between px-4 py-4 transition active:bg-gray-50"
          >
            <div className="flex items-center gap-3">
              <svg className="h-5 w-5 text-gray-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" /><polyline points="14 2 14 8 20 8" /><line x1="16" y1="13" x2="8" y2="13" /><line x1="16" y1="17" x2="8" y2="17" />
              </svg>
              <span className="text-[15px] text-gray-800">Terms of Use</span>
            </div>
            <ChevronRight className="h-4 w-4 text-gray-400" />
          </button>
          <div className="mx-4 h-px bg-gray-100" />
          <button
            onClick={() => setSubPage('privacy')}
            className="flex w-full items-center justify-between px-4 py-4 transition active:bg-gray-50"
          >
            <div className="flex items-center gap-3">
              <svg className="h-5 w-5 text-gray-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">
                <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
              </svg>
              <span className="text-[15px] text-gray-800">Privacy Policy</span>
            </div>
            <ChevronRight className="h-4 w-4 text-gray-400" />
          </button>
        </div>

        {/* Help */}
        <div className="mb-6 overflow-hidden rounded-2xl bg-white">
          <button
            onClick={() => setSubPage('help')}
            className="flex w-full items-center justify-between px-4 py-4 transition active:bg-gray-50"
          >
            <div className="flex items-center gap-3">
              <svg className="h-5 w-5 text-gray-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="10" /><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" /><line x1="12" y1="17" x2="12.01" y2="17" />
              </svg>
              <span className="text-[15px] text-gray-800">Help &amp; Feedback</span>
            </div>
            <ChevronRight className="h-4 w-4 text-gray-400" />
          </button>
        </div>

        <p className="text-center text-[11px] text-gray-400">
          AI-generated content is for reference only. Use legally.
        </p>
      </div>

      {/* Version toast */}
      {versionToast && (
        <div className="pointer-events-none fixed bottom-24 left-1/2 z-50 -translate-x-1/2 rounded-2xl bg-gray-900 px-5 py-3 text-[14px] font-medium text-white shadow-xl">
          You are already on the latest version.
        </div>
      )}
    </div>
  )
          }
      
